import "./global.css";
import { Inter } from "next/font/google";
import ProviderClient from "../components/Login/ProviderClient";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/Login/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spartan Budget",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProviderClient>
        <SessionProvider session={session}>{children}</SessionProvider>
        </ProviderClient>
      </body>
    </html>
  );
}
